export const ADMIN_FORM_DESC = [
	{
		entity: "FieldDefinition",
		order: 1,
		field: "id",
		pk: true,
		type: "N",
		rel_entity: null,
		list: null,
		multiple: null,
		min: null,
		max: null,
		readonly: true,
		picker_col: true,
		filter: null,
		info: null,
		comment: null,
	},

	{
		entity: "FieldDefinition",
		order: 2,
		field: "entity",
		pk: false,
		type: "T",
		rel_entity: null,
		list: null,
		multiple: null,
		min: null,
		max: null,
		readonly: false,
		picker_col: true,
		filter: null,
		info: null,
		comment: null,
	},
	
	{
		entity: "FieldDefinition",
		order: 3,
		field: "order",
		pk: false,
		type: "N",
		rel_entity: null,
		list: null,
		multiple: null,
		min: null,
		max: null,
		readonly: false,
		picker_col: true,
		filter: null,
		info: null,
		comment: null,
	},
	
	{
		entity: "FieldDefinition",
		order: 4,
		field: "field",
		pk: false,
		type: "T",
		rel_entity: null,
		list: null,
		multiple: null,
		min: null,
		max: null,
		readonly: false,
		picker_col: false,
		filter: null,
		info: null,
		comment: null,
	},
	
	{
		entity: "FieldDefinition",
		order: 5,
		field: "pk",
		pk: false,
		type: "B",
		rel_entity: null,
		list: null,
		multiple: null,
		min: null,
		max: null,
		readonly: false,
		picker_col: false,
		filter: null,
		info: null,
		comment: null,
	},
	
	{
		entity: "FieldDefinition",
		order: 6,
		field: "type",
		pk: false,
		type: "T",
		rel_entity: null,
		list: null,
		multiple: null,
		min: null,
		max: null,
		readonly: false,
		picker_col: false,
		filter: null,
		info: null,
		comment: null,
	},
	
	{
		entity: "FieldDefinition",
		order: 7,
		field: "list",
		pk: false,
		type: "T",
		rel_entity: null,
		list: null,
		multiple: null,
		min: null,
		max: null,
		readonly: false,
		picker_col: false,
		filter: null,
		info: null,
		comment: null,
	},
	
	{
		entity: "FieldDefinition",
		order: 8,
		field: "rel_entity",
		pk: false,
		type: "T",
		rel_entity: null,
		list: null,
		multiple: null,
		min: null,
		max: null,
		readonly: false,
		picker_col: false,
		filter: null,
		info: null,
		comment: null,
	},
	
	{
		entity: "FieldDefinition",
		order: 9,
		field: "multiple",
		pk: false,
		type: "B",
		rel_entity: null,
		list: null,
		multiple: null,
		min: null,
		max: null,
		readonly: false,
		picker_col: false,
		filter: null,
		info: null,
		comment: null,
	},
	
	{
		entity: "FieldDefinition",
		order: 10,
		field: "min",
		pk: false,
		type: "N",
		rel_entity: null,
		list: null,
		multiple: null,
		min: null,
		max: null,
		readonly: false,
		picker_col: false,
		filter: null,
		info: null,
		comment: null,
	},
	
	{
		entity: "FieldDefinition",
		order: 11,
		field: "max",
		pk: false,
		type: "N",
		rel_entity: null,
		list: null,
		multiple: null,
		min: null,
		max: null,
		readonly: false,
		picker_col: false,
		filter: null,
		info: null,
		comment: null,
	},
	
	{
		entity: "FieldDefinition",
		order: 12,
		field: "readonly",
		pk: false,
		type: "B",
		rel_entity: null,
		list: null,
		multiple: null,
		min: null,
		max: null,
		readonly: false,
		picker_col: false,
		filter: null,
		info: null,
		comment: null,
	},
	
	{
		entity: "FieldDefinition",
		order: 13,
		field: "picker_col",
		pk: false,
		type: "B",
		rel_entity: null,
		list: null,
		multiple: null,
		min: null,
		max: null,
		readonly: false,
		picker_col: false,
		filter: null,
		info: null,
		comment: null,
	},
	
	{
		entity: "FieldDefinition",
		order: 14,
		field: "filter",
		pk: false,
		type: "T",
		rel_entity: null,
		list: null,
		multiple: null,
		min: null,
		max: null,
		readonly: false,
		picker_col: false,
		filter: null,
		info: null,
		comment: null,
	},
	
	{
		entity: "FieldDefinition",
		order: 15,
		field: "info",
		pk: false,
		type: "T",
		rel_entity: null,
		list: null,
		multiple: null,
		min: null,
		max: null,
		readonly: false,
		picker_col: false,
		filter: null,
		info: null,
		comment: null,
	},
	
	{
		entity: "FieldDefinition",
		order: 16,
		field: "comment",
		pk: false,
		type: "T",
		rel_entity: null,
		list: null,
		multiple: null,
		min: null,
		max: null,
		readonly: false,
		picker_col: false,
		filter: null,
		info: null,
		comment: null,
	},
	
];


export const CATEGORY_FORM_DESC = [
	{
		entity: "FieldDefinition",
		order: 1,
		field: "id",
		pk: true,
		type: "N",
		rel_entity: null,
		list: null,
		multiple: null,
		min: null,
		max: null,
		readonly: true,
		picker_col: true,
		filter: null,
		info: null,
		comment: null,
	},
	
	{
		entity: "FieldDefinition",
		order: 2,
		field: "name",
		pk: false,
		type: "T",
		rel_entity: null,
		list: null,
		multiple: null,
		min: null,
		max: null,
		readonly: false,
		picker_col: true,
		filter: null,
		info: null,
		comment: null,
	},

	{
		entity: "FieldDefinition",
		order: 3,
		field: "info",
		pk: false,
		type: "T",
		rel_entity: null,
		list: null,
		multiple: null,
		min: null,
		max: null,
		readonly: false,
		picker_col: true,
		filter: null,
		info: null,
		comment: null,
	},
	
	{
		entity: "FieldDefinition",
		order: 4,
		field: "isFavorite",
		pk: false,
		type: "B",
		rel_entity: null,
		list: null,
		multiple: null,
		min: null,
		max: null,
		readonly: false,
		picker_col: true,
		filter: null,
		info: null,
		comment: null,
	},

]

