gantt
    title Plan with todayMarker
    todayMarker stroke-width:10px,stroke:black,opacity:0.5
    axisFormat %a %d
    section Phase-A
        Task 1 : 2025-11-03, 5d
        Task 2 : 2025-11-03, 1d